### ISSUE TITLE
Cannot locate object

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/nagiosToCentreon#1]
Hi,

Got the following error / message, it could help you:
Can't locate object method "contactgroup_name" via package "grp_piquet" (perhaps you forgot to load "grp_piquet"?) at /tmp/nagios_reader_to_centreon_clapi.pl line 343.

grp_piquet est un groupe de contact.

Thanks

**Comment by lpinsivy** [comment]
Hi can you send me a zip of Nagios etc directory by email to make some test ?

Can you specify your Nagios server OS distribution and version and the Nagios version?

**Comment by matthieu-robin** [comment]
sent by mail

**Comment by lpinsivy** [comment]
Merci Matthieu je vais débuger ca ;)

2015-12-08 17:06 GMT+01:00 matthieu-robin notifications@github.com:

> sent by mail
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/centreon/nagiosToCentreon/issues/1#issuecomment-162930211
> .

## 

_Laurent PINSIVY Project Manager & Head of Professional Services_

Email: lpinsivy@centreon.com
Tel +33 (0) 1 49 69 97 12
Fax +33 (0) 1 78 12 00 28

[image: Centreon_Logo_RVB_Light_200x76px.png]
Centreon - Your IT co-pilot
www.centreon.com | blog.centreon.com | github.com/centreon

**Comment by matthieu-robin** [comment]
Avec plaisir!
Bon, pas sur que je l’utilise pour cette migration car vu qu’on a le droit au plugin packs, je vais en profiter pour tout refaire propre chez le client :-)

Mais pour le futur!

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com
