### ISSUE TITLE
Can't call method "service_name" on unblessed

### ISSUE THREAD

**Issue by Jaspper** [centreon/nagiosToCentreon#10]
Hello ,
I got this error message when executing the script: 

Can't call method "service_name" on unblessed reference at /root/nagiosToCentreon-master/nagios_reader_to_centreon_clapi.pl line 706.

It's related to the export of servicegroups, but I couldn't figure out what's wrong in the code.

Any help plz !!

**Comment by lpinsivy** [comment]
Hi
I discovered many strange behavior on the Nagios::Config library that I used to prepare Centreon Clapi commands.

Some time the array is juste a string, some time a simple array, and other time an hash array.

As I can't create all the Nagios configurations, I need you to debug. Can you send me your configuration by MP (it will only be used for testing) to reproduce the behavior?

Regards,

**Comment by fmorisseau** [comment]
Hi, 

I've encountered the very same issue.
I'm new at perl so thank u for the tip : it helps a lot to narrow the bug down.

Regards,

**Comment by acamilleri** [comment]
Hello,

I got the same error ...
Can't call method "service_name" on unblessed reference at nagios_reader_to_centreon_clapi.pl line 714.

**Comment by lpinsivy** [comment]
Hi guys

I need your Nagios config directory to debug. Can you send me your configuration ?

regards,

**Comment by acamilleri** [comment]
Bonjour,

J'ai vu que vous étiez français donc ça m'arrange de parler en français :P

Quand vous parlez de configuration, vous parlez de nagios.cfg ??

Je vous enverrai ce dont vous avez besoin dès demain

J'utilise votre module pour migrer de nagios-centreon installé avec la CES
et pouvoir passer sur la dernière version de centreon ;)

Merci d'avance,
Cordialement,
Alexis
Le 1 févr. 2016 5:34 PM, "Laurent Pinsivy" notifications@github.com a
écrit :

**Comment by lpinsivy** [comment]
Bonjour,

Il me faut l’intégralité de votre configuration Nagios (tous le répertoire "etc" contenant tous les fichiers CFG) afin de comprendre pourquoi certaines erreurs sont remontées. Vous pouvez m'envoyer un zip par mail.

**Comment by acamilleri** [comment]
Bonjour,

Qu'elle est votre adresse email ?

**Comment by lpinsivy** [comment]
lpinsivy [at] centreon.com

**Comment by acamilleri** [comment]
C'est envoyé

**Comment by kobol56** [comment]
Bonjour,

Je rencontre exactement le même soucis.
Si besoin je peux également envoyer mes fichiers de configuration.

Merci
