### ISSUE TITLE
Can't call method "use" 

### ISSUE THREAD

**Issue by marcinbednarski** [centreon/nagiosToCentreon#15]
Hi, I have an issue on CentOS 6.4.. Nagios upgraded to 4.1.1, Nagios-Object-0.21.20 installed.

perl nagios_reader_to_centreon_clapi.pl --config /usr/local/nagios/etc/nagios.cfg > /tmp/cntreon_clapi_import_commands.txt
Can't call method "use" without a package or object reference at nagios_reader_to_centreon_clapi.pl line 475.

**Comment by marcinbednarski** [comment]
..some more details from debugger:
  DB<10> c
Can't call method "use" without a package or object reference at nagios_reader_to_centreon_clapi.pl line 475.
 at nagios_reader_to_centreon_clapi.pl line 475
        main::export_services(0) called at nagios_reader_to_centreon_clapi.pl line 476
        main::export_services('Nagios::Service=HASH(0x14c23f0)', 'Nagios::Service=HASH(0x14c2408)', 'Nagios::Service=HASH(0x14c2900)', 'Nagios::Service=HASH(0x14c2a38)', 'Nagios::Service=HASH(0x14c2f90)', 'Nagios::Service=HASH(0x14c60f8)', 'Nagios::Service=HASH(0x1513db8)', 'Nagios::Service=HASH(0x1513fe0)', 'Nagios::Service=HASH(0x1514148)', ...) called at nagios_reader_to_centreon_clapi.pl line 752

Could you help please?

**Comment by Tulan** [comment]
I confirm the same problem, impossible to convert hosts and services configuration files.

**Comment by teleko** [comment]
Hello, 
Did you find a solution for this problem?

Thanks

**Comment by cgagnaire** [comment]
Hi @marcinbednarski, @Tulan and @teleko,
Can you please try the v3-sims branch that fix your problem ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
