### ISSUE TITLE
Export limits at 2000 + Object not found:Nagios::Contact=HASH(0x930f850)

### ISSUE THREAD

**Issue by Bibelo** [centreon/nagiosToCentreon#16]
Hello,

I've successfully imported my configuration from an old Nagios server, and managed to make all check works.

But I notice that not all services have been imported from the old configuration. When I checked the file generated by the script nagios_reader_to_centreon_clapi.pl, I see a sharp 2000 services imported, when there are 2324 on my old Centreon.

[root@tom nagiosToCentreon]# grep "SERVICE;ADD" exportclapi | wc -l
2000

So it seems there's some kind of limitation here?

---

Another problem I have, is when I import this file in the new Centreon, I've got quite a bunch of these message :

Line 15425 : Object not found:Nagios::Contact=HASH(0x930f850)

Do you know by anychance what they mean?

Thank you very much in advance!

**Comment by ErrafayM** [comment]
I have same issue , have you found a solution ?

**Comment by cgagnaire** [comment]
Hi @Bibelo,
Can you please try the v3-sims branch that fix your problem ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
