### ISSUE TITLE
Unable to export service if servicetemplate have same name

### ISSUE THREAD

**Issue by lpinsivy** [centreon/nagiosToCentreon#18]
It's impossible to export a service if a service template has the same name

**Comment by homer2012** [comment]
Hello,

Thanks for this update. It generate on error for me

perl nagios_reader_to_centreon_clapi.pl -S --config /etc/nagios3/nagios.cfg > /tmp/centreon_clapi_import_commands.txt
Use of uninitialized value $name in exists at /usr/local/share/perl/5.10.1/Nagios/Object/Config.pm line 367.
Can't call method "register" without a package or object reference at nagios_reader_to_centreon_clapi.pl line 490.

It occures at the second service :

define service{
host_name Switch Fibre1
service_description PING_SWITCHES
is_volatile 0
check_period 24x7
max_check_attempts 10
normal_check_interval 5
retry_check_interval 1
contact_groups switches
notification_options w,u,c,r
notification_interval 960
notification_period 24x7
check_command check_ping!1000.0,50%!5000.0,100%
}

define service{
host_name Switch Fibre2
service_description PING_SWITCHES
is_volatile 0
check_period 24x7
max_check_attempts 10
normal_check_interval 5
retry_check_interval 1
contact_groups switches
notification_options w,u,c,r
notification_interval 960
notification_period 24x7
check_command check_ping!1000.0,50%!5000.0,100%
}

**Comment by homer2012** [comment]
for the first error, i saw your workaround at #9. Seems to work.

But i steel have the error on register line 490.

**Comment by KarlisSe** [comment]
Did you ever resolved your problem on `register` line 490? I`m encountering the same error.

**Comment by homer2012** [comment]
No, finally i used this script and manualy modify the result before import.
