### ISSUE TITLE
Can't locate object method "name" via package

### ISSUE THREAD

**Issue by ccadenel** [centreon/nagiosToCentreon#19]
When try to generate clapi file I recevie this error message:
Can't locate object method "name" via package "xxxxx" 

xxxx is a contact name

**Comment by ErrafayM** [comment]
Have you fixed this issue ? i'm running the same error.

**Comment by kwoltz1984** [comment]
I am getting this error as well:
Can't locate object method "name" via package "HelpDesk" (perhaps you forgot to load "HelpDesk"?) at /tmp/nagiosToCentreon/nagios_reader_to_centreon_clapi.pl line 672.

It looks like line 672 involves adding the contacts to services.  "HelpDesk" is one of our contacts.

We are running Centreon 2.3.8 with Nagios 3.5.1.  Trying to get this configuration so we can start using CES.

**Comment by Ejant** [comment]
Same issue here....
Can't locate object method "name" via package "nagiosadmin" (perhaps you forgot to load "nagiosadmin"?) at nagios_reader_to_centreon_clapi.pl line 361.

"nagiosadmin" is a contact

**Comment by Ejant** [comment]
it looks like the error comes when there are multiple contacts:

HTPL;setcontactgroup;HOST;CONTACTGROUPS;
Can't locate object method "name" via package "nagiosadmin" (perhaps you forgot to load "nagiosadmin"?) at nagios_reader_to_centreon_clapi.pl line 361.

so, i look into my file and

define host{
        name                            HOST
        use                             generic-host
        alias                           HOST
        _SNMPCOMMUNITY                  TCBW-nocalert
        contact_groups                  Contact_A,Contact_B
        contacts                                nagiosadmin,someuser
        notification_period             24x7
        register                                0
}

If i leave only one contact, it works ok

**Comment by kwoltz1984** [comment]
This worked for me, thanks!  Mine was with a service though instead of a host.  I had one service with multiple contacts and "HelpDesk" was the first one.  I removed the other contact and reran with success.  No more errors!  Thanks @Ejant !

**Comment by cgagnaire** [comment]
Hi @ccadenel, @kwoltz1984 and @Ejant,
Can you please try the v3-sims branch that fix your problem ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!

**Comment by Ejant** [comment]
@cgagnaire it's working now, thank you!!!
