### ISSUE TITLE
Unable to export services with same description name.

### ISSUE THREAD

**Issue by ErrafayM** [centreon/nagiosToCentreon#21]
Hi , i'm having an issue exporting Services with same description name. to make it sample to understand here's an exemple : 

Server 1 :  
PING
CPU
RAM 

Server 2 : 
PING
CPU 
RAM 

I'll be unable to export Server 2 services , because they have same description name with Server 1. the workaround i did is to rename the Server 2 services (Srv2_Ping, Srv2_CPU, Srv2_RAM) to be able to export them. 

If it can help i have CentOS 5.9 with A Fully Automated Nagios Running Nagios 3.4.4, trying to export them to my CES 3.3.

**Comment by DanSmall** [comment]
I can confirm this bug. I am having the same problem.

**Comment by ErrafayM** [comment]
Thank you! i will try to test your fix as soon as possible. 

EDIT : 

Seems to be working for me, thank you again. :+1:
