### ISSUE TITLE
Can't call method "use" without a package or object reference at nagios_reader_to_centreon_clapi.pl line 481.

### ISSUE THREAD

**Issue by teleko** [centreon/nagiosToCentreon#29]
Hello,

I received the error below when trying to export Nagios 4 configuration.
Do you have any idea on this?

Thanks.

**Comment by cgagnaire** [comment]
Hi @dbonengel,
Can you please try the v3-sims branch ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!

**Comment by cgagnaire** [comment]
Hi @teleko,
Can you please try the v3-sims branch ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
