### ISSUE TITLE
Error message during execution

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/nagiosToCentreon#3]
Hi,
Here is the message:
Use of uninitialized value $value in pattern match (m//) at /usr/lib/perl5/site_perl/5.14.2/Nagios/Object.pm line 860, <GEN13> line 14580.

If it's help you Laurent :-)

Thanks

**Comment by lpinsivy** [comment]
Issue with Nagios::Object library, you can try this modification

--- /usr/local/share/perl5/Nagios/Object.pm.origin      2015-12-10 13:43:00.295008617 +0100
+++ /usr/local/share/perl5/Nagios/Object.pm     2015-12-10 13:41:25.633870322 +0100
@@ -857,11 +857,11 @@

```
 # Nagios allows the usage of a '+' sign. This breaks member lists.
 # Ignore the '+' sign completely for now.
```
-    if ( ref $vf->{$key}[0] eq 'ARRAY' && $value =~/^+(.+)$/ ) {
-    if ( ref $vf->{$key}[0] eq 'ARRAY' && defined ($value) && $value =~/^+(.+)$/ ) {
       $value = $1;
   }
-    if ( ref $vf->{$key}[0] eq 'ARRAY' && $value =~ /,/ ) {
-    if ( ref $vf->{$key}[0] eq 'ARRAY' && defined($value) && $value =~ /,/ ) {
       $value = [ split /\s_,\s_/, $value ];
   }
