### ISSUE TITLE
Can't call method "use" without a package or object reference at nagios_reader_to_centreon_clapi.pl line 484

### ISSUE THREAD

**Issue by teleko** [centreon/nagiosToCentreon#30]
Hello,

Error again on line 484 when trying to convert Nagios config files.

Thanks, 
Daniel

**Comment by cgagnaire** [comment]
Hi @teleko,
Can you please try the v3-sims branch ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
