### ISSUE TITLE
Can't locate object method "members" via package "allhosts"

### ISSUE THREAD

**Issue by pepitomuler** [centreon/nagiosToCentreon#32]
Can't locate object method "members" via package "allhosts" (perhaps you forgot to load "allhosts"?) at nagios_reader_to_centreon_clapi.pl line 381.

The hosts and the services ar not exported in the txt file, it's stop after Host Templates

**Comment by tsingletonacic** [comment]
Not a solution to the issue, but I found a workaround by commenting the "all" hostgroup definition

**Comment by pepitomuler** [comment]
Where do you comment the "all" hostgroup definition ? In the nagios .cfg files ?

**Comment by tsingletonacic** [comment]
Yes, I commented in the nagios file prior to running the convert tool

**Comment by pepitomuler** [comment]
Could you tell me wich cfg file ? I do not find it

**Comment by tsingletonacic** [comment]
Sure,
My version of nagios is quite old, but I commented these lines : 
define hostgroup {
        hostgroup_name  all
		alias           All Servers
		members         *
        }

in the file /etc/nagios2/conf.d/hostgroups_nagios2.cfg 

Best

**Comment by pepitomuler** [comment]
Yes it works ! Thanks a lot
