### ISSUE TITLE
script consumes all memory

### ISSUE THREAD

**Issue by wpsentinel** [centreon/nagiosToCentreon#37]
hello,

I don't know if it's related to the script itself or my servers but when I execute '**perl nagios_reader_to_centreon_clapi.pl --config /usr/local/nagios/etc/nagios.cfg > /tmp/centreon_clapi_import_commands.txt**'  I quickly get an out of memory message and the script never finishes :(

I'm trying to import nagios 4.0.8 configuration to a freshly installed Centreon 3.4
Nagios VM runs on CentOS7. It has 2 vcpu and 4Gb of memory. My Nagios configuration has something like 80 hosts so I don't think it's a huge configuration. 
Any idea? 
Thank you

**Comment by cgagnaire** [comment]
Hi @draugr333,
Can you please try the v3-sims branch ?
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
