### ISSUE TITLE
contact admin

### ISSUE THREAD

**Issue by arnaud-michel** [centreon/nagiosToCentreon#38]
All imported contact are desactivated in the Clapi (line 167)
printf ( "CONTACT;setparam;%s;contact_activate;0\n", $contact_name); 
When you import your clapi, if you had a admin user in your target Centreon, you are not able to connect anymore on your system. You have to activate your admin user through MySQL to recover connection.
Why do you desactivate user contact in this script ?
Could you exclude admin contact from desactivation in this script.

**Comment by cgagnaire** [comment]
Hi @arnaud-michel,
Done in v3-sims branch, you may want to try it.
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
