### ISSUE TITLE
contacts : Full Name and Alias inversed

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/nagiosToCentreon#4]
All is in the title :-)

thanks

**Comment by micwiel** [comment]
I confirm this bug.

**Comment by DanSmall** [comment]
I can confirm this bug too. I am having the same problem.

**Comment by cgagnaire** [comment]
Hi everyone,
Well, that's kind of true, but some configurations swapped those two values.
This is handled in the v3-sims branch, you may want to test it.
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
And if you encounter a "swapped configuration", you can use the option --swap.
Thanks!
