### ISSUE TITLE
Can't locate object method - hostgroups

### ISSUE THREAD

**Issue by btassite** [centreon/nagiosToCentreon#6]
Hi,

I'm getting a similar error to issue #5  but in a different section (the version of the script I downloaded ("1.0") already contains nountevo's patch):

`Can't locate object method "members" via package "all" (perhaps you forgot to load "all"?) at nagios_reader_to_centreon_clapi.pl line 369.`

When I comment out the offending section (in `/etc/nagios3/conf.d/hostgroups_nagios2.cfg`) the script continues (with other errors, will submit new issues for those), but misses the All group with everything in it (hosts, services):

```
# A simple wildcard hostgroup
#define hostgroup {
#        hostgroup_name  all
#               alias           All Servers
#               members         *
#        }
```

**Comment by cgagnaire** [comment]
Hi @btassite,
It is now handled in the v3-sims branch, you may want to try it.
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.
Thanks!
