### ISSUE TITLE
Can't use an undefined value as an ARRAY reference

### ISSUE THREAD

**Issue by btassite** [centreon/nagiosToCentreon#8]
After commenting out the offending stanza for issue #6, I get instead:

`Can't use an undefined value as an ARRAY reference at nagios_reader_to_centreon_clapi.pl_orig line 560.`

Almost all services are missing from the output.

**Comment by cgagnaire** [comment]
Hi @btassite,
Can you please try the v3-sims branch that fix your problem ?
Thanks!

**Comment by cgagnaire** [comment]
Be advise that the --config option now needs the path to the configuration files objects directory, not the nagios.cfg.

**Comment by btassite** [comment]
Sorry, I can no longer help you with debugging since we have moved completely off Nagios and the old configs have no relevance to the much changed new environment anymore.

**Comment by cgagnaire** [comment]
Hey, no worries!
Sorry, I must have spammed you through the other issues :)
