### ISSUE TITLE
Use of uninitialized value $name in exists at ../Nagios/Object/Config.pm

### ISSUE THREAD

**Issue by btassite** [centreon/nagiosToCentreon#9]
I get 9 of these lines (right before the errors in issue #6 an #7):

`Use of uninitialized value $name in exists at /usr/local/share/perl/5.20.2/Nagios/Object/Config.pm line 367.`

**Comment by lpinsivy** [comment]
Hi btassite,

I never seen this issue. I need a complete Nagios configuration to perform tests.

Can you send my your by MP to reproduce issue ? Your configuration will be used only for debug.

Regards,

**Comment by lpinsivy** [comment]
Hi,
you can use thi patch

--- /usr/local/share/perl5/Nagios/Object/Config.pm.orig 2016-02-01 09:54:12.926460291 +0000
+++ /usr/local/share/perl5/Nagios/Object/Config.pm      2016-02-01 13:22:03.047330943 +0000
@@ -364,7 +364,7 @@

```
 if ( $type && $type =~ /^Nagios::(.*)/ ) {
     my $index_type = lc($1) . '_index';
```
-        if ( exists $self->{$index_type} && exists $self->{$index_type}->{$name} ) {
-        if ( exists $self->{$index_type} && defined ($name) && exists $self->{$index_type}->{$name} ) {
            return @{$self->{$index_type}->{$name}};
       }
   }
